version: "3.3"

services:
  app:
    build: ./
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app/server
      - ./pages:/usr/src/app/pages
      - ./components:/usr/src/app/components
      - ./layouts:/usr/src/app/layouts
    depends_on: 
      - redis
    links:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]

